# Generated by Django 5.1.6 on 2025-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nombres',
            field=models.CharField(default='jorgeSalazar', max_length=100),
            preserve_default=False,
        ),
    ]
