# Generated by Django 5.1.6 on 2025-04-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_contacto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='direccion_entrega',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
