# Generated by Django 5.1.6 on 2025-05-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_remove_contacto_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaCliente',
        ),
    ]
