# Generated by Django 5.1.6 on 2025-05-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_remove_documentoid_cod_ce_remove_documentoid_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoid',
            name='contacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='clientes_app.contacto'),
        ),
    ]
