# Generated by Django 5.1.6 on 2025-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0007_contacto_cod_dni_contacto_cod_ruc_delete_documentoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='cod_dni',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='cod_ruc',
        ),
        migrations.AddField(
            model_name='contacto',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=3),
        ),
    ]
