# Generated by Django 5.1.6 on 2025-05-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0008_remove_contacto_cod_dni_remove_contacto_cod_ruc_and_more'),
        ('oportunidades_app', '0010_rename_contacto_oportunidad_cliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Cliente',
        ),
    ]
