import { z } from "zod";

const UnidadMedida = z.object({
    codigo: z.string(),
    descripcion: z.string(),
})

type TUnidadMedida = z.infer<typeof UnidadMedida>

export const UNIDADES_MEDIDA: TUnidadMedida[] = [
  { codigo: '4A', descripcion: 'BOBINAS' },
  { codigo: 'BJ', descripcion: 'BALDE' },
  { codigo: 'BLL', descripcion: 'BARRILES' },
  { codigo: 'BG', descripcion: 'BOLSA' },
  { codigo: 'BO', descripcion: 'BOTELLAS' },
  { codigo: 'BX', descripcion: 'CAJA' },
  { codigo: 'CT', descripcion: 'CARTONES' },
  { codigo: 'CMK', descripcion: 'CENTIMETRO CUADRADO' },
  { codigo: 'CMQ', descripcion: 'CENTIMETRO CUBICO' },
  { codigo: 'CMT', descripcion: 'CENTIMETRO LINEAL' },
  { codigo: 'CEN', descripcion: 'CIENTO DE UNIDADES' },
  { codigo: 'CY', descripcion: 'CILINDRO' },
  { codigo: 'CJ', descripcion: 'CONOS' },
  { codigo: 'DZN', descripcion: 'DOCENA' },
  { codigo: 'DZP', descripcion: 'DOCENA POR 10**6' },
  { codigo: 'BE', descripcion: 'FARDO' },
  { codigo: 'GLI', descripcion: 'GALON INGLES (4,545956L)' },
  { codigo: 'GRM', descripcion: 'GRAMO' },
  { codigo: 'GRO', descripcion: 'GRUESA' },
  { codigo: 'HLT', descripcion: 'HECTOLITRO' },
  { codigo: 'LEF', descripcion: 'HOJA' },
  { codigo: 'SET', descripcion: 'JUEGO' },
  { codigo: 'KGM', descripcion: 'KILOGRAMO' },
  { codigo: 'KTM', descripcion: 'KILOMETRO' },
  { codigo: 'KWH', descripcion: 'KILOVATIO HORA' },
  { codigo: 'KT', descripcion: 'KIT' },
  { codigo: 'CA', descripcion: 'LATAS' },
  { codigo: 'LBR', descripcion: 'LIBRAS' },
  { codigo: 'LTR', descripcion: 'LITRO' },
  { codigo: 'MWH', descripcion: 'MEGAWATT HORA' },
  { codigo: 'MTR', descripcion: 'METRO' },
  { codigo: 'MTK', descripcion: 'METRO CUADRADO' },
  { codigo: 'MTQ', descripcion: 'METRO CUBICO' },
  { codigo: 'MGM', descripcion: 'MILIGRAMOS' },
  { codigo: 'MLT', descripcion: 'MILILITRO' },
  { codigo: 'MMT', descripcion: 'MILIMETRO' },
  { codigo: 'MMK', descripcion: 'MILIMETRO CUADRADO' },
  { codigo: 'MMQ', descripcion: 'MILIMETRO CUBICO' },
  { codigo: 'MLL', descripcion: 'MILLARES' },
  { codigo: 'UM', descripcion: 'MILLON DE UNIDADES' },
  { codigo: 'ONZ', descripcion: 'ONZAS' },
  { codigo: 'PF', descripcion: 'PALETAS' },
  { codigo: 'PK', descripcion: 'PAQUETE' },
  { codigo: 'PR', descripcion: 'PAR' },
  { codigo: 'FOT', descripcion: 'PIES' },
  { codigo: 'FTK', descripcion: 'PIES CUADRADOS' },
  { codigo: 'FTQ', descripcion: 'PIES CUBICOS' },
  { codigo: 'C62', descripcion: 'PIEZAS' },
  { codigo: 'PG', descripcion: 'PLACAS' },
  { codigo: 'ST', descripcion: 'PLIEGO' },
  { codigo: 'INH', descripcion: 'PULGADAS' },
  { codigo: 'RM', descripcion: 'RESMA' },
  { codigo: 'DR', descripcion: 'TAMBOR' },
  { codigo: 'STN', descripcion: 'TONELADA CORTA' },
  { codigo: 'LTN', descripcion: 'TONELADA LARGA' },
  { codigo: 'TNE', descripcion: 'TONELADAS' },
  { codigo: 'TU', descripcion: 'TUBOS' },
  { codigo: 'NIU', descripcion: 'UNIDAD (BIENES)' },
  { codigo: 'ZZ', descripcion: 'UNIDAD (SERVICIOS)' },
  { codigo: 'GLL', descripcion: 'US GALON (3,7843 L)' },
  { codigo: 'YRD', descripcion: 'YARDA' },
  { codigo: 'YDK', descripcion: 'YARDA CUADRADA' },
];

export const UNIDADES_MEDIDA_BUSCA: Record<string,string> = {
  '4A':  'BOBINAS' ,
  'BJ':  'BALDE' ,
  'BLL': 'BARRILES' ,
  'BG':  'BOLSA' ,
  'BO':  'BOTELLAS' ,
  'BX':  'CAJA' ,
  'CT':  'CARTONES' ,
  'CMK': 'CENTIMETRO CUADRADO' ,
  'CMQ': 'CENTIMETRO CUBICO' ,
  'CMT': 'CENTIMETRO LINEAL' ,
  'CEN': 'CIENTO DE UNIDADES' ,
  'CY':  'CILINDRO' ,
  'CJ':  'CONOS' ,
  'DZN': 'DOCENA' ,
  'DZP': 'DOCENA POR 10**6' ,
  'BE':  'FARDO' ,
  'GLI': 'GALON INGLES (4,545956L)' ,
  'GRM': 'GRAMO' ,
  'GRO': 'GRUESA' ,
  'HLT': 'HECTOLITRO' ,
  'LEF': 'HOJA' ,
  'SET': 'JUEGO' ,
  'KGM': 'KILOGRAMO' ,
  'KTM': 'KILOMETRO' ,
  'KWH': 'KILOVATIO HORA' ,
  'KT':  'KIT' ,
  'CA':  'LATAS' ,
  'LBR': 'LIBRAS' ,
  'LTR': 'LITRO' ,
  'MWH': 'MEGAWATT HORA' ,
  'MTR': 'METRO' ,
  'MTK': 'METRO CUADRADO' ,
  'MTQ': 'METRO CUBICO' ,
  'MGM': 'MILIGRAMOS' ,
  'MLT': 'MILILITRO' ,
  'MMT': 'MILIMETRO' ,
  'MMK': 'MILIMETRO CUADRADO' ,
  'MMQ': 'MILIMETRO CUBICO' ,
  'MLL': 'MILLARES' ,
  'UM':  'MILLON DE UNIDADES' ,
  'ONZ': 'ONZAS' ,
  'PF':  'PALETAS' ,
  'PK':  'PAQUETE' ,
  'PR':  'PAR' ,
  'FOT': 'PIES' ,
  'FTK': 'PIES CUADRADOS' ,
  'FTQ': 'PIES CUBICOS' ,
  'C62': 'PIEZAS' ,
  'PG':  'PLACAS' ,
  'ST':  'PLIEGO' ,
  'INH': 'PULGADAS' ,
  'RM':  'RESMA' ,
  'DR':  'TAMBOR' ,
  'STN': 'TONELADA CORTA' ,
  'LTN': 'TONELADA LARGA' ,
  'TNE': 'TONELADAS' ,
  'TU':  'TUBOS' ,
  'NIU': 'UNIDAD (BIENES)' ,
  'ZZ':  'UNIDAD (SERVICIOS)' ,
  'GLL': 'US GALON (3,7843 L)' ,
  'YRD': 'YARDA' ,
  'YDK': 'YARDA CUADRADA' ,

}