# Generated by Django 5.1.6 on 2025-06-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dgeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_RUC', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=250)),
                ('nombre_comercial', models.CharField(max_length=250)),
                ('direccion_fiscal', models.CharField(max_length=350)),
                ('margen_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('dgeneral_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='ajustes_app.dgeneral')),
            ],
        ),
    ]
