# Generated by Django 5.1.6 on 2025-06-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='dgeneral_id',
            new_name='dgeneral',
        ),
    ]
