# Generated by Django 5.1.6 on 2025-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_rename_categoria_id_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_comprometida',
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
