# Generated by Django 5.1.6 on 2025-05-08 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_remove_producto_precio_producto_es_servicio_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precio',
            old_name='precio',
            new_name='valor',
        ),
        migrations.AlterField(
            model_name='precio',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventario_app.producto'),
        ),
    ]
