# Generated by Django 5.1.6 on 2025-05-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0005_rename_precio_precio_valor_alter_precio_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inventario', to='inventario_app.producto'),
        ),
    ]
