# Generated by Django 5.1.6 on 2025-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0006_inventario_activo_alter_inventario_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
