###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "giogio", "password":"pass123"}


###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username": "yosep", "password": "Contra123", "email": "yosep.h@gmail.com"}


###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

###
GET http://127.0.0.1:8000/usuarios/roles
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

###
POST http://127.0.0.1:8000/usuarios/roles/
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

{
    "name": "Administrador",
    "permission_ids": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
                     21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,
                     39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,
                     57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
                     75,76,77,78,79,80]
}

###
GET http://127.0.0.1:8000/usuarios/permisos
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

###
GET http://127.0.0.1:8000/usuarios/usuarios
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

###
PUT http://127.0.0.1:8000/usuarios/usuarios/2/
Content-Type: application/json
Authorization: Token 3c19a9b914689d0e87c89f5a7f0bba771dad7941

{
    "id": 2,
    "username": "giogio",
    "groups": ["Administrador"]
}