###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "yosep", "password":"Contra123"}


###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username": "yosep", "password": "Contra123", "email": "yosep.h@gmail.com"}


###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token f19175b6c60612542e4a85e0880424c352300a0e
