# Generated by Django 5.1.6 on 2025-03-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oportunidades_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido_fechaentrega', models.DateField(blank=True, null=True)),
                ('pedido_direccion', models.CharField(max_length=255)),
                ('moneda', models.CharField(default='PEN', max_length=5)),
                ('RUC_emisor', models.CharField(max_length=11)),
                ('DOC_cliente', models.CharField(max_length=20)),
                ('monto_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(default='contado', max_length=50)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('despachado', 'Despachado'), ('anulado', 'Anulado')], default='pendiente', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGV', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('codigo_tributo', models.CharField(default='1000', max_length=10)),
                ('descuento_adicional', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='oportunidades_app.oportunidad')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nrolinea', models.PositiveBigIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.pedido')),
            ],
        ),
    ]
