# Generated by Django 5.1.6 on 2025-03-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_fechaentrega',
            new_name='fechaentrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='cli', max_length=255),
        ),
    ]
