# Generated by Django 5.1.6 on 2025-03-04 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0005_alter_oportunidad_vendedor_asignado'),
        ('ventas_app', '0002_rename_pedido_direccion_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cotizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='oportunidades_app.cotizacion'),
        ),
    ]
