# Generated by Django 5.1.6 on 2025-03-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_alter_pedido_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='cod_producto',
            field=models.IntegerField(default=1),
        ),
    ]
