# Generated by Django 5.1.6 on 2025-04-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0005_alter_pedidodetalle_cod_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_despacho',
        ),
    ]
