# Generated by Django 5.1.6 on 2025-05-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_remove_producto_precio_producto_es_servicio_precio'),
        ('ventas_app', '0006_remove_pedido_fecha_despacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='IGV',
            new_name='monto_igv',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_detalle', to='inventario_app.producto'),
            preserve_default=False,
        ),
    ]
