# Generated by Django 5.1.6 on 2025-05-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0007_rename_igv_pedido_monto_igv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='DOC_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='RUC_emisor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pago',
        ),
    ]
