# Generated by Django 5.1.6 on 2025-05-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0008_remove_pedido_doc_cliente_remove_pedido_ruc_emisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='codigo_tributo',
            new_name='codigo_tipo_tributo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='correlativo',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='serie',
            field=models.CharField(default='B001', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura', 'factura'), ('boleta', 'boleta')], default='boleta', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
