# Generated by Django 5.1.6 on 2025-06-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_app', '0001_initial'),
        ('ventas_app', '0009_rename_codigo_tributo_pedido_codigo_tipo_tributo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura', 'factura'), ('boleta', 'boleta'), ('nota_credito_boleta', 'nota_credito_boleta'), ('nota_debito_boleta', 'nota_debito_boleta'), ('nota_credito_factura', 'nota_credito_factura'), ('nota_debito_factura', 'nota_debito_factura')], max_length=50),
        ),
        migrations.CreateModel(
            name='SerieCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('factura', 'factura'), ('boleta', 'boleta'), ('nota_credito_boleta', 'nota_credito_boleta'), ('nota_debito_boleta', 'nota_debito_boleta'), ('nota_credito_factura', 'nota_credito_factura'), ('nota_debito_factura', 'nota_debito_factura')], max_length=50)),
                ('serie', models.CharField(max_length=10)),
                ('ultimo_correlativo', models.IntegerField(default=0)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_correlativos', to='ajustes_app.sede')),
            ],
        ),
    ]
