# Generated by Django 5.1.6 on 2025-06-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0011_seriecorrelativo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='documento_referencia',
            field=models.ForeignKey(blank=True, help_text='Pedido original al que se asocia esta nota de crédito o débito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_asociadas', to='ventas_app.pedido'),
        ),
    ]
