# Generated by Django 5.1.6 on 2025-06-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0012_oportunidad_sede'),
        ('ventas_app', '0012_pedido_documento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cotizacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='oportunidades_app.cotizacion'),
        ),
    ]
