# Generated by Django 5.1.6 on 2025-06-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0013_alter_pedido_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_nota',
            field=models.CharField(choices=[('anulacion de la operacion', 'anulacion de la operacion'), ('anulacion por ruc erroneo', 'anulacion por ruc erroneo'), ('decuento global', 'decuento global'), ('descuento por item', 'descuento por item'), ('devolucion total', 'devolucion total'), ('aumento en el valor', 'aumento en el valor')], max_length=50, null=True),
        ),
    ]
