# Generated by Django 5.1.6 on 2025-06-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0014_pedido_tipo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='documento_referencia',
            field=models.ForeignKey(blank=True, help_text='Pedido original al que se asocia esta nota de crédito o debito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_asociadas', to='ventas_app.pedido'),
        ),
    ]
