# Generated by Django 5.1.6 on 2025-03-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado_cotizacion', models.CharField(choices=[('nueva', 'Nueva'), ('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='nueva', max_length=20)),
                ('validez', models.IntegerField()),
                ('monto_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IGV', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nrolinea', models.PositiveBigIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='oportunidades_app.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_detalle', to='inventario_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_contacto', models.DateField()),
                ('vendedor_asignado', models.IntegerField(null=True)),
                ('estado_oportunidad', models.CharField(choices=[('nuevo', 'Nuevo'), ('en negociacion', 'En Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.contacto')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='oportunidades_app.oportunidad'),
        ),
    ]
