# Generated by Django 5.1.6 on 2025-03-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado_oportunidad',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('negociacion', 'En Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20),
        ),
    ]
