# Generated by Django 5.1.6 on 2025-03-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0002_alter_oportunidad_estado_oportunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='resultado',
        ),
    ]
