# Generated by Django 5.1.6 on 2025-03-04 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_contacto_categoria'),
        ('oportunidades_app', '0003_remove_oportunidad_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.contacto'),
        ),
    ]
