# Generated by Django 5.1.6 on 2025-03-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0004_alter_oportunidad_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='vendedor_asignado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
