# Generated by Django 5.1.6 on 2025-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0005_alter_oportunidad_vendedor_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado_oportunidad',
            field=models.CharField(choices=[('nueva', 'Nuevo'), ('negociacion', 'En Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nueva', max_length=20),
        ),
    ]
