# Generated by Django 5.1.6 on 2025-04-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0006_alter_oportunidad_estado_oportunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='direccion_entrega',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
