# Generated by Django 5.1.6 on 2025-05-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0007_cotizacion_descuento_adicional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='IGV',
            new_name='monto_igv',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='propuesta', max_length=20),
        ),
    ]
