# Generated by Django 5.1.6 on 2025-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0008_rename_igv_cotizacion_monto_igv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptada', 'Aceptada')], default='propuesta', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado_oportunidad',
            field=models.CharField(choices=[('negociacion', 'En Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='negociacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_contacto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
