# Generated by Django 5.1.6 on 2025-05-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades_app', '0009_alter_cotizacion_estado_cotizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidad',
            old_name='contacto',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='validez',
        ),
        migrations.RemoveField(
            model_name='oportunidad',
            name='valor_neto',
        ),
        migrations.RemoveField(
            model_name='oportunidad',
            name='vendedor_asignado',
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
