# Generated by Django 5.1.6 on 2025-05-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0009_rename_contacto_cliente'),
        ('oportunidades_app', '0010_rename_contacto_oportunidad_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='propuesta', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes_app.cliente'),
        ),
    ]
