# Generated by Django 5.1.6 on 2025-06-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes_app', '0001_initial'),
        ('oportunidades_app', '0011_alter_cotizacion_estado_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ajustes_app.sede'),
            preserve_default=False,
        ),
    ]
