# Generated by Django 5.1.6 on 2025-06-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_app', '0007_alter_precio_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_fijo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad_pagada', models.IntegerField()),
                ('cantidad_libre', models.IntegerField()),
                ('cantidad_libre_maxima', models.IntegerField()),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo'), ('cantidad', 'Por Cantidad')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='inventario_app.producto')),
            ],
        ),
    ]
