# Generated by Django 5.1.6 on 2025-06-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladescuento',
            name='cantidad_libre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='cantidad_libre_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='cantidad_pagada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='monto_fijo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
